### ISSUE TITLE
Bot responds to message containing only spaces and/or line breaks

### ISSUE THREAD

**Issue by Jorenar** [OK-bot-team/uj-discord-bot#29]
For example, for `;ok~~ ;`  
we get the following black image:
![](https://cdn.discordapp.com/attachments/926656958327566366/926656964015034438/image.png)

---

If we add new lines:
```
;ok~~

;
```
the image is bigger:
![](https://cdn.discordapp.com/attachments/905911679244718160/926655093783269376/image.png)

**Comment by tdadela** [comment]
It’s not a bug, it’s a feature.
It allows users to express themselves via pure background images.
