### ISSUE TITLE
Support for unicode characters is lacking

### ISSUE THREAD

**Issue by Jorenar** [OK-bot-team/uj-discord-bot#31]
For example, for `;ok~~ 道路標識;` instead of hanzi generated is the following:
![](https://cdn.discordapp.com/attachments/926656958327566366/926660287845793803/image.png)

**Comment by skyman503** [comment]
it's all about finding a better font, won't fix polish language works.

**Comment by tdadela** [comment]
Thanks.
I'll try to fix it in the next month.
